# Generated by Django 5.2.5 on 2025-08-28 14:49

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EUDRDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[('Arabica', 'Arabica'), ('Robusta', 'Robusta'), ('Blend', 'Blend')], default='Arabica', max_length=20)),
                ('total_kilograms', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supplier_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('documentation_receipts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of receipt references', size=None)),
                ('documentation_notes', models.TextField(blank=True, help_text='Additional notes or remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_category', models.CharField(blank=True, choices=[('GR', 'Green Coffee'), ('PA', 'Parchment Coffee'), ('KB', 'Kiboko Coffee')], max_length=2, verbose_name='Coffee Form')),
                ('coffee_type', models.CharField(choices=[('ARABICA', 'Arabica'), ('ROBUSTA', 'Robusta'), ('BLEND', 'Blend')], default='ARABICA', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Coffee Inventory',
                'ordering': ['coffee_category', 'coffee_type'],
                'unique_together': {('coffee_category', 'coffee_type')},
            },
        ),
        migrations.CreateModel(
            name='CoffeeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('coffee_category', models.CharField(blank=True, choices=[('GR', 'Green Coffee'), ('PA', 'Parchment Coffee'), ('KB', 'Kiboko Coffee')], max_length=2, verbose_name='Coffee Form')),
                ('coffee_type', models.CharField(choices=[('AR', 'Arabica'), ('RB', 'Robusta')], default='AR', max_length=2)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coffee Sale',
                'verbose_name_plural': 'Coffee Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coffee Supplier',
                'verbose_name_plural': 'Coffee Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoffeePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_category', models.CharField(blank=True, choices=[('GR', 'Green Coffee'), ('PA', 'Parchment Coffee'), ('KB', 'Kiboko Coffee')], max_length=2, verbose_name='Coffee Form')),
                ('coffee_type', models.CharField(choices=[('AR', 'Arabica'), ('RB', 'Robusta')], default='AR', max_length=2)),
                ('quantity', models.DecimalField(decimal_places=0, help_text='Weight in kilograms', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bags', models.PositiveIntegerField(default=0, help_text='Number of bags (if applicable)', validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('D', 'Paid'), ('T', 'Partial')], default='P', max_length=1, verbose_name='Payment Status')),
                ('assessment_needed', models.BooleanField(default=True, verbose_name='Quality Assessment')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='store.supplier')),
            ],
            options={
                'verbose_name': 'Coffee Purchase',
                'verbose_name_plural': 'Coffee Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='store.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('transaction_type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='store.supplieraccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_transactions', to='store.coffeepurchase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='coffeepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0.01)), name='quantity_gte_001'),
        ),
    ]
