# Generated by Django 5.2.5 on 2025-09-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_coffeepurchase_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoffeeInventory',
        ),
        migrations.DeleteModel(
            name='CoffeeSale',
        ),
    ]
