# Generated by Django 5.2.5 on 2025-08-30 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessment_options_assessment_assessed_by_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='coffee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assessment', to='store.coffeepurchase'),
            preserve_default=False,
        ),
    ]
