# Generated by Django 5.2.5 on 2025-09-10 08:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_assessment_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='below_screen_12',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Below Screen 12 (%)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='discretion',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=12, verbose_name='Discretion (UGX)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='fm',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Foreign Matter (%)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='group1_defects',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Group 1 Defects (%)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='group2_defects',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Group 2 Defects (%)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='husks',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Husks (%)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='moisture_content',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Moisture (%)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Offered Price (UGX)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='pods',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Pods (%)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='ref_price',
            field=models.PositiveIntegerField(help_text='Reference Price (UGX)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='stones',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Stones (%)'),
        ),
    ]
