# Generated by Django 5.2.5 on 2025-09-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_assessment_below_screen_12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='offered_price',
            field=models.PositiveIntegerField(blank=True, help_text='Offered Price (UGX)'),
        ),
    ]
