# Generated by Django 5.2.5 on 2025-09-16 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='expense_type',
            field=models.CharField(choices=[('AIRTIME_DATA', 'Airtime/Data'), ('OVERTIME_PAYMENT', 'Overtime Payment'), ('FIELD_OPERATIONS', 'Field Operations'), ('TRANSPORT_FUEL', 'Transport/Fuel'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('MEALS_REFRESHMENTS', 'Meals/Refreshments'), ('ACCOMMODATION', 'Accommodation'), ('EQUIP_VEH_MAINT', 'Equipment/Vehicle Maintenance'), ('UTILITIES_PAYMENT', 'Utilities Payment'), ('OTHER_EXPENSES', 'Other Expenses')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='expenserequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='expenses_ex_request_016708_idx'),
        ),
        migrations.DeleteModel(
            name='ExpenseType',
        ),
    ]
