# Generated by Django 5.2.5 on 2025-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenserequest_expense_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallog',
            options={'ordering': ['-acted_at'], 'verbose_name': 'Approval Log', 'verbose_name_plural': 'Approval Logs'},
        ),
        migrations.AlterModelOptions(
            name='expenseattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Expense Attachment', 'verbose_name_plural': 'Expense Attachments'},
        ),
        migrations.AlterModelOptions(
            name='expenserequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expense Request', 'verbose_name_plural': 'Expense Requests'},
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='requires_admin_approval',
            field=models.BooleanField(default=False, help_text='Auto-true for bank transfers; usable by workflows/guards.'),
        ),
    ]
