# Generated by Django 5.2.5 on 2025-09-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_approvallog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='description',
        ),
    ]
