# Generated by Django 5.2.5 on 2025-09-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('access_sales', 'Can access sales app'), ('access_inventory', 'Can access inventory app'), ('access_reports', 'Can access reports app'), ('access_assessment', 'Can access assessment app'), ('access_analysis', 'Can access analysis app'), ('access_accounts', 'Can access accounts app'), ('access_finance', 'Can access finance app'), ('access_milling', 'Can access milling app'), ('access_store', 'Can access store app'), ('access_expenses', 'Can access expenses app')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
