# Generated by Django 5.2.5 on 2025-09-15 07:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeinventory',
            name='average_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weighted average (UGX per unit).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='coffeeinventory',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: quantity × average_unit_cost.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='coffeeinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='On-hand quantity.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
