# Generated by Django 5.2.5 on 2025-09-08 14:44

import django.core.validators
import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('coffee_type', models.CharField(choices=[('DRUGAR', 'Drugar (Arabica FAQ)'), ('WASHED', 'Washed (Parchment)'), ('ROBUSTA_FAQ', 'Robusta FAQ'), ('ROBUSTA_SCR15', 'Robusta Screen 15+'), ('OTHER', 'Other')], default='DRUGAR', max_length=32)),
                ('average_buying_price_ugx_per_kg', models.DecimalField(decimal_places=2, default=0, help_text='UGX per kg', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('kilograms_bought', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('kilograms_sold', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_bags_sold', models.PositiveIntegerField(default=0)),
                ('bags_left_in_store', models.PositiveIntegerField(default=0)),
                ('kilograms_left_in_store', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('kilograms_unbought_in_store', models.DecimalField(decimal_places=2, default=0, help_text='Coffee present but not yet bought/processed', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_to', models.CharField(blank=True, max_length=255)),
                ('advances_given_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('attachment', models.FileField(blank=True, null=True, upload_to=reports.models.report_upload_to)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_by', models.ForeignKey(help_text='The staff user who entered this report', on_delete=django.db.models.deletion.PROTECT, related_name='daily_store_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'coffee_type'], name='reports_dai_date_26d33e_idx')],
                'unique_together': {('date', 'coffee_type')},
            },
        ),
    ]
