# Generated by Django 5.2.5 on 2025-09-09 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millingprocess',
            name='hulled_weight',
            field=models.PositiveIntegerField(default=0, help_text='Coffee quantity in kilograms', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='millingprocess',
            name='initial_weight',
            field=models.PositiveIntegerField(default=0, help_text='Coffee quantity in kilograms', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
