# Generated by Django 5.2.5 on 2025-09-15 06:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Customer Name')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone / Contact')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sales_salec_name_2cf595_idx'), models.Index(fields=['contact'], name='sales_salec_contact_cc9237_idx'), models.Index(fields=['email'], name='sales_salec_email_eadfd5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='salecustomer_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='CoffeeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, help_text='Date the sale was recorded (local time).', verbose_name='Sale Date')),
                ('coffee_type', models.CharField(choices=[('AR', 'Arabica'), ('RB', 'Robusta')], default='AR', help_text='Select coffee type', max_length=2, verbose_name='Coffee Type')),
                ('moisture_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Enter moisture percentage (0–100).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Moisture (%)')),
                ('quantity_kg', models.DecimalField(decimal_places=2, help_text='Enter weight in kg.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight (kg)')),
                ('unit_price_ugx', models.DecimalField(decimal_places=2, help_text='Enter unit price.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Unit Price (UGX/kg)')),
                ('truck_details', models.CharField(help_text='Truck number plate, capacity, etc.', max_length=255, verbose_name='Truck Details')),
                ('driver_details', models.CharField(help_text='Driver name and phone number.', max_length=255, verbose_name='Driver Details')),
                ('sales_grn', models.FileField(blank=True, null=True, upload_to='sales_grn/', verbose_name='Upload Sales GRN (Optional)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this sale.', on_delete=django.db.models.deletion.PROTECT, related_name='coffee_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Buyer / consignee for this sale.', on_delete=django.db.models.deletion.PROTECT, related_name='coffee_sales', to='sales.salecustomer')),
            ],
            options={
                'verbose_name': 'Coffee Sale',
                'verbose_name_plural': 'Coffee Sales',
                'ordering': ['-sale_date', '-created_at'],
                'indexes': [models.Index(fields=['sale_date'], name='sales_coffe_sale_da_54ef16_idx'), models.Index(fields=['customer', 'sale_date'], name='sales_coffe_custome_bcb80f_idx'), models.Index(fields=['coffee_type'], name='sales_coffe_coffee__7313bd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='coffeesale_quantity_kg_gt_0'), models.CheckConstraint(condition=models.Q(('unit_price_ugx__gt', 0)), name='coffeesale_unit_price_ugx_gt_0')],
            },
        ),
    ]
